### PR TITLE
Update blank.yaml

### PR DESCRIPTION
**Pull request by yuya-takeyama**
Just added, not tested in any implementations.
Considering how to do it.

### CODE REVIEW

**Comment by yuya-takeyama** [comment]
@tagomoris My work has done.
Could you review it?

* blank string, hyphen and `null` is treated as blank
* all fields of the result is filled with `UNKNOWN`

And I noticed that no implementations have tests for blank cases.
It should be fixed to.

**Comment by tagomoris** [comment]
Seems good.
Please squash commits.

**Comment by yuya-takeyama** [comment]
@tagomoris squashed!

**Comment by tagomoris** [comment]
:+1:

**Comment by tagomoris** [comment]
We need issues about this change on each language implementations.

**Pull request merged**
