### PR TITLE
Add trendictionbot crawler

### PR DESCRIPTION
**Pull request by ryukobayashi**
I added the following crawler bot: http://www.trendiction.com/en/publisher/bot
Could you review this?

### CODE REVIEW

**Comment by tagomoris** [comment]
`category: crawler` looks missing

**Comment by tagomoris** [comment]
Oops, I missed that this change doesn't add an entry about `trandictionbot` into `dataset.yml`.

**Comment by tagomoris** [comment]
Done: e84a3cedc774dcef93893192e7362d8d23e357aa

**Comment by ryukobayashi** [comment]
👍

**Pull request merged**
